### ISSUE TITLE
Скрытие части юзердаты от пользователя

### ISSUE THREAD

**Issue by MarkShidran** [profcomff/userdata-api#14]
В юзердате слишком много разных полей. Далеко не все надо показывать пользователю. Например, если мы при оаутхе через тг получили ник в тг, пользователю не надо показывать его в профиле, т.к. это бесполезная инфа для него. Пользователю скорее полезно знать, что он авторизован через тг

**Comment by dyakovri** [comment]
Добавление флага скрытости параметра
Параметр может быть скрытым от пользователя и не отдаваться пользователю, если у него нет права на чтение этой категории

То есть добавить новое поле в параметр isHidden
Если поле X находится в категории Y, доступ на чтение которой требует иметь scope userdata.Y.get, то
- Пользователь получит поле X, если у него есть скоуп userdata.Y.get
- Пользователь не сможет посмотреть поле X, если у него нет скоупа userdata.Y.get, даже если он владелец этих данных

**Comment by grigoriev-semyon** [comment]
1. Добавить в параметр поле `visible_in_user_response`
2. Добавить в ручку `GET /user/{id}` в Query string список невидимых по дефолту параметров, которые надо отдать. Назвать его `additional_data`, под дефолту - пустой список
Формат задания параметра: `additional_data=category1.field1, category1.field2, category2.field1`.
При запросе данных по дефолту будут отдаваться только поля с `visible_in_user_response=True`. Если поле указано в запросе `GET /user/{id}` в соответствующем Query параметре, то его тоже отдать
3. Добавить поле в хэндлер создания параметра, получения параметра. Дефолтное значение при создании - `True`
