### ISSUE TITLE
Батчевое получение всех пользователей

### ISSUE THREAD

**Issue by MarkShidran** [profcomff/userdata-api#39]
Добавить ручку GET для получения всех пользователей. Сейчас есть только ручка для получения пользователей по ID.

**Comment by grigoriev-semyon** [comment]
Необходимо добавить ручку `GET /user` ответом которой будут вообще все пользовательские данные которые доступны админу. Ручку закрыть под скоуп `userdata.info.admin`. Отдавать категории необходимо только если есть право на чтение этой категории у данного админа

Ответ отдавать в формате json. Формат такой: словарь, ключ id пользователя, значение - взять из ответа `GET /user/{id}`. То есть response.user_id.items будет списком соответственных json с ключами category, param, value

Данные отдавать в соответствии с их полями all, most_trusted, last

Также в ручку добавить query параметры users и categories, обязательные параметры, передается туда список запрашиваемых пользовательских айди и список запрашиваемых категорий. В соответствии с этими полями отдавать данные
