### ISSUE TITLE
В requirements.txt нет `pydantic-settings`

### ISSUE THREAD

**Issue by annndruha** [profcomff/userdata-api#6]
В requirements.txt нет `pydantic-settings`, хотя в коде используются. Вопрос скорее следующий: как оно завелось и сбилдилось?

**Comment by MarkShidran** [comment]
@grigoriev-semyon, тут даже какие-то странные сроки стоят на задаче. Ты не брался за нее?

**Comment by grigoriev-semyon** [comment]
> @grigoriev-semyon, тут даже какие-то странные сроки стоят на задаче. Ты не брался за нее?


я сделал уже в a02db706e7b1ec216c2ee5b346db149ede6c616f
